const GITHUB_EMOJI_MAP: Record<string, string> = {
  ":hash:": "#️⃣",
  ":books:": "📚",
  ":book:": "📖",
  ":robot:": "🤖",
  ":building_construction:": "🏗️",
  ":hospital:": "🏥",
  ":moneybag:": "💰",
  ":money_with_wings:": "💸",
  ":zap:": "⚡",
  ":seedling:": "🌱",
  ":ear_of_rice:": "🌾",
  ":cityscape:": "🏙️",
  ":globe_with_meridians:": "🌐",
  ":rocket:": "🚀",
  ":airplane:": "✈️",
  ":art:": "🎨",
  ":tv:": "📺",
  ":factory:": "🏭",
  ":bulb:": "💡",
  ":speech_balloon:": "💬",
  ":mega:": "📢",
  ":pray:": "🙏",
  ":raised_hands:": "🙌",
  ":ballot_box:": "🗳️",
  ":earth_africa:": "🌍",
  ":earth_americas:": "🌎",
  ":earth_asia:": "🌏",
  ":star:": "⭐",
  ":star2:": "🌟",
  ":hammer_and_wrench:": "🛠️",
  ":microscope:": "🔬",
  ":test_tube:": "🧪",
  ":dna:": "🧬",
  ":stethoscope:": "🩺",
  ":scales:": "⚖️",
  ":classical_building:": "🏛️",
  ":mortar_board:": "🎓",
  ":computer:": "💻",
  ":shield:": "🛡️",
  ":link:": "🔗",
  ":gear:": "⚙️",
  ":chart_with_upwards_trend:": "📈",
  ":handshake:": "🤝",
  ":people_holding_hands:": "🧑‍🤝‍🧑",
  ":deciduous_tree:": "🌳",
  ":national_park:": "🏞️",
  ":heart:": "❤️",
  ":sunny:": "☀️",
  ":wind_face:": "🌬️",
  ":ocean:": "🌊",
  ":recycle:": "♻️",
};

export function resolveEmoji(input: string): string {
  if (!input) return "";
  if (!input.startsWith(":")) return input;
  const resolved = GITHUB_EMOJI_MAP[input.toLowerCase()];
  if (resolved) return resolved;
  return input.replace(/:/g, "").trim();
}
